### ISSUE TITLE
Poco version differs from tutorial

### ISSUE THREAD

**Issue by ArekPiekarz** [memsharded/example-poco-timer#5]
The tutorial on http://docs.conan.io/en/latest/getting_started.html contains a following conanfile.txt:

```
 [requires]
 Poco/1.8.0.1@pocoproject/stable

 [generators]
 cmake
```

while the file in this repository has an older version of library:

```
 [requires]
 Poco/1.7.9@pocoproject/stable

 [generators]
 cmake
```

Cloning this repository is listed as one of the ways to gather the example files, so they should be kept in sync or the tutorial should be rewritten.

**Comment by memsharded** [comment]
Thanks very much for noticing @ArekPiekarz 
Yes, this repo was outdated, it should have been updated at the same time as the docs. 
Fixed.
