### ISSUE TITLE
Outdated dependency

### ISSUE THREAD

**Issue by eric-bixby** [memsharded/example-poco-timer#7]
I had two problems with the following in conanfile.txt:
Poco/1.9.0@pocoproject/stable

1) Looks like 1.9.0 is outdated, might want to update to 1.9.4
2) I had to remove "@pocoproject/stable"; it's available on bintray.com

**Comment by memsharded** [comment]
Yes, this is some legacy in the docs. We are moving all examples for the docs to an updated repo. 

I have just updated the docs accordingly in https://github.com/conan-io/docs/commit/e478dc5dd8acca0adfabbf7d92f40bf4bf176a2c, so this, my own repo shouldn't be used anymore.

There are still other references to some other of my repos in the docs. They are likely to be outdated too, we will be moving them to the examples repo too.

Thanks for reporting!

**Comment by eric-bixby** [comment]
Got it, thanks
